export var TaskIds = {
  VISIT_DOCTOR: 'VISIT_DOCTOR',
  EAT_CANNED_FOOD: 'EAT_CANNED_FOOD',
  VISIT_THERAPIST: 'VISIT_THERAPIST'
}

export var EffectTypes = {
  ADD_MOD: 'ADD_MOD',
  REMOVE_MOD: 'REMOVE_MOD',
  REVEAL_MOD: 'REVEAL_MOD'
}
