export var TaskIds = {
  VISIT_DOCTOR: 'VISIT_DOCTOR',
  EAT_CANNED_FOOD: 'EAT_CANNED_FOOD',
  VISIT_THERAPIST: 'VISIT_THERAPIST'
}

export var EffectTypes = {
  EFFECT_TYPE_ADD_MOD: 'ADD_MOD',
  EFFECT_TYPE_REMOVE_MOD: 'REMOVE_MOD',
  EFFECT_TYPE_REVEAL_MOD: 'REVEAL_MOD'
}
